"""empty message

Revision ID: 08949d015f8f
Revises: 
Create Date: 2019-08-04 13:07:53.883888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08949d015f8f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=64), nullable=True),
    sa.Column('definition', sa.String(length=256), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_word_word'), 'word', ['word'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_word_word'), table_name='word')
    op.drop_table('word')
    # ### end Alembic commands ###
